# Generated by Django 5.1.7 on 2025-03-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_icon',
            field=models.ImageField(blank=True, null=True, upload_to='post_icons/'),
        ),
    ]
